version: '3.8'

services:

  frontend:
    image: jonatanRamirez/frontend:1.0
    container_name: frontend
    ports:
      - "8000:80" # Exponer el puerto 80 del contenedor en el puerto 3000 de la máquina
  
    depends_on:
      - backend  
    networks:
      - app-network

  mysql:
    image: jonatanRamirez/mysql:1.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456DAW.
      MYSQL_DATABASE: listaProductos
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"  # Exponer MySQL en el puerto 3307 de la máquina
    networks:
      - app-network

  backend:
    
    image: jonatanRamirez/backend:1.0
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/listaProductos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456DAW.
    ports:
      - "8081:8080"  # Exponer la aplicación Spring Boot en el puerto 8081
    depends_on:
      - mysql  # Asegurarse de que MySQL se inicie antes que la aplicación Spring Boot
    networks:
      - app-network

networks:
  app-network:  # Se elimina la especificación del driver
volumes:
  mysql-data:  # Se elimina la especificación del driver