version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456DAW.
      MYSQL_DATABASE: listaProductos
    ports:
      - "3307:3306"  # Exponer MySQL en el puerto 3307
    networks:
      - app-network

  back:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/listaProductos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456DAW.
    ports:
      - "8081:8080"  # Exponer la aplicación Spring Boot en el puerto 8081
    depends_on:
      - mysql  # Asegurarse de que MySQL se inicie antes que la aplicación Spring Boot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
